apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: signer
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebelarte-tenant/nvidia-build-sign-rhtap/signer@sha256:54a2d2e8e5aa15e683a0e0d19fe4663278a8dd522a0834aaff06fee6fc4a94ac
        name: container-image
        resources: {}
status: {}
