apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: signer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signer
    app.kubernetes.io/part-of: nvidia-build-sign-rhtap
  name: signerebcf
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: signer
    weight: 100
status: {}
